name: Node build
run-name: Build nodejs app
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest  # Cambiado de [self-hosted] a ubuntu-latest
    steps:
      - name: Descargar el repo
        uses: actions/checkout@v4
      - name: Usar nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: Instalar dependencias
        working-directory: ./calculadora
        run: npm install
      - name: Dar permisos a binarios
        working-directory: ./calculadora
        run: chmod +x node_modules/.bin/*
      - name: Ejecutar lint
        working-directory: ./calculadora
        run: npm run lint
 