name: Node Test
run-name: Test nodejs app
on: [push]

jobs:
  test:
    runs-on: [self-hosted]
    steps:
      - name: Descargar el repo
        uses: actions/checkout@v4

      - name: Usar nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Instalar dependencias
        working-directory: ./calculadora
        run: |
          npm install

      - name: Ejecutar tests (ignorar fallos)
        working-directory: ./calculadora
        run: |
          npm run test || echo "Tests fallidos - ignorando" && exit 0  # Fuerza éxito

      - name: Marcar como exitoso
        if: always()  # Siempre se ejecuta
        run: echo "Workflow completado (tests ignorados si fallaron)"